###############################################################################
# Created by write_sdc
###############################################################################
current_design microwatt
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name ext_clk -period 15.0000 [get_ports {ext_clk}]
set_clock_transition 0.1500 [get_clocks {ext_clk}]
set_clock_uncertainty 0.2500 ext_clk
set_propagated_clock [get_clocks {ext_clk}]
create_clock -name jtag_tck -period 100.0000 [get_ports {jtag_tck}]
set_clock_transition 0.1500 [get_clocks {jtag_tck}]
set_clock_uncertainty 0.2500 jtag_tck
set_propagated_clock [get_clocks {jtag_tck}]
set_clock_groups -name group1 -logically_exclusive \
 -group [get_clocks {ext_clk}]\
 -group [get_clocks {jtag_tck}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {ext_rst}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[0]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[10]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[11]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[12]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[13]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[14]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[15]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[16]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[17]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[18]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[19]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[1]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[20]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[21]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[22]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[23]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[24]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[25]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[26]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[27]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[28]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[29]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[2]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[30]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[31]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[3]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[4]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[5]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[6]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[7]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[8]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_in[9]}]
set_input_delay 20.0000 -clock [get_clocks {jtag_tck}] -add_delay [get_ports {jtag_tdi}]
set_input_delay 20.0000 -clock [get_clocks {jtag_tck}] -add_delay [get_ports {jtag_tms}]
set_input_delay 20.0000 -clock [get_clocks {jtag_tck}] -add_delay [get_ports {jtag_trst}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_in[0]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_in[1]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_in[2]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_in[3]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_in[4]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_in[5]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_in[6]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_in[7]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_irq}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_parity_in}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_i[0]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_i[1]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_i[2]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_i[3]}]
set_input_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {uart0_rxd}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[0]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[10]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[11]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[12]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[13]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[14]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[15]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[16]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[17]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[18]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[19]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[1]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[20]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[21]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[22]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[23]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[24]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[25]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[26]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[27]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[28]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[29]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[2]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[30]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[31]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[3]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[4]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[5]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[6]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[7]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[8]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_dir[9]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[0]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[10]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[11]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[12]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[13]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[14]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[15]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[16]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[17]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[18]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[19]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[1]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[20]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[21]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[22]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[23]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[24]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[25]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[26]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[27]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[28]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[29]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[2]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[30]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[31]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[3]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[4]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[5]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[6]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[7]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[8]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {gpio_out[9]}]
set_output_delay 20.0000 -clock [get_clocks {jtag_tck}] -add_delay [get_ports {jtag_tdo}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_out[0]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_out[1]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_out[2]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_out[3]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_out[4]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_out[5]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_out[6]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_bus_out[7]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_clk}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_enabled}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {simplebus_parity_out}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_clk}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_cs_n}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_o[0]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_o[1]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_o[2]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_o[3]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_oe[0]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_oe[1]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_oe[2]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {spi_flash_sdat_oe[3]}]
set_output_delay 3.0000 -clock [get_clocks {ext_clk}] -add_delay [get_ports {uart0_txd}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {jtag_tdo}]
set_load -pin_load 0.0334 [get_ports {simplebus_clk}]
set_load -pin_load 0.0334 [get_ports {simplebus_enabled}]
set_load -pin_load 0.0334 [get_ports {simplebus_parity_out}]
set_load -pin_load 0.0334 [get_ports {spi_flash_clk}]
set_load -pin_load 0.0334 [get_ports {spi_flash_cs_n}]
set_load -pin_load 0.0334 [get_ports {uart0_txd}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[31]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[30]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[29]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[28]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[27]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[26]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[25]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[24]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[23]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[22]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[21]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[20]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[19]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[18]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[17]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[16]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[15]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[14]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[13]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[12]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[11]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[10]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[9]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[8]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[7]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[6]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[5]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[4]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[3]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[2]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[1]}]
set_load -pin_load 0.0334 [get_ports {gpio_dir[0]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[31]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[30]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[29]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[28]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[27]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[26]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[25]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[24]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[23]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[22]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[21]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[20]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[19]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[18]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[17]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[16]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[15]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[14]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[13]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[12]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[11]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[10]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[9]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[8]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[7]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[6]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[5]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[4]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[3]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[2]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[1]}]
set_load -pin_load 0.0334 [get_ports {gpio_out[0]}]
set_load -pin_load 0.0334 [get_ports {simplebus_bus_out[7]}]
set_load -pin_load 0.0334 [get_ports {simplebus_bus_out[6]}]
set_load -pin_load 0.0334 [get_ports {simplebus_bus_out[5]}]
set_load -pin_load 0.0334 [get_ports {simplebus_bus_out[4]}]
set_load -pin_load 0.0334 [get_ports {simplebus_bus_out[3]}]
set_load -pin_load 0.0334 [get_ports {simplebus_bus_out[2]}]
set_load -pin_load 0.0334 [get_ports {simplebus_bus_out[1]}]
set_load -pin_load 0.0334 [get_ports {simplebus_bus_out[0]}]
set_load -pin_load 0.0334 [get_ports {spi_flash_sdat_o[3]}]
set_load -pin_load 0.0334 [get_ports {spi_flash_sdat_o[2]}]
set_load -pin_load 0.0334 [get_ports {spi_flash_sdat_o[1]}]
set_load -pin_load 0.0334 [get_ports {spi_flash_sdat_o[0]}]
set_load -pin_load 0.0334 [get_ports {spi_flash_sdat_oe[3]}]
set_load -pin_load 0.0334 [get_ports {spi_flash_sdat_oe[2]}]
set_load -pin_load 0.0334 [get_ports {spi_flash_sdat_oe[1]}]
set_load -pin_load 0.0334 [get_ports {spi_flash_sdat_oe[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {alt_reset}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ext_clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ext_rst}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {jtag_tck}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {jtag_tdi}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {jtag_tms}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {jtag_trst}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_irq}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_parity_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uart0_rxd}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {gpio_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_bus_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_bus_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_bus_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_bus_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_bus_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_bus_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_bus_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {simplebus_bus_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {spi_flash_sdat_i[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {spi_flash_sdat_i[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {spi_flash_sdat_i[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {spi_flash_sdat_i[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
