###############################################################################
# Created by write_sdc
###############################################################################
current_design register_file
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name core_clock -period 1.0000 [get_ports {clk}]
set_propagated_clock [get_clocks {core_clock}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr1[0]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr1[1]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr1[2]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr1[3]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr1[4]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr2[0]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr2[1]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr2[2]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr2[3]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_addr2[4]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_en1}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_en2}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {rst_n}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_addr[0]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_addr[1]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_addr[2]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_addr[3]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_addr[4]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[0]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[10]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[11]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[12]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[13]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[14]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[15]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[16]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[17]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[18]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[19]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[1]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[20]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[21]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[22]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[23]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[24]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[25]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[26]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[27]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[28]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[29]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[2]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[30]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[31]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[3]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[4]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[5]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[6]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[7]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[8]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_data[9]}]
set_input_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {write_en}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[0]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[10]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[11]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[12]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[13]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[14]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[15]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[16]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[17]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[18]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[19]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[1]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[20]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[21]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[22]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[23]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[24]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[25]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[26]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[27]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[28]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[29]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[2]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[30]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[31]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[3]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[4]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[5]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[6]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[7]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[8]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data1[9]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[0]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[10]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[11]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[12]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[13]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[14]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[15]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[16]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[17]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[18]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[19]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[1]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[20]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[21]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[22]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[23]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[24]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[25]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[26]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[27]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[28]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[29]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[2]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[30]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[31]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[3]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[4]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[5]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[6]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[7]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[8]}]
set_output_delay 0.2000 -clock [get_clocks {core_clock}] -add_delay [get_ports {read_data2[9]}]
###############################################################################
# Environment
###############################################################################
###############################################################################
# Design Rules
###############################################################################
